import View from '@/View/View.js'
import State from '@/State/State.js'

export default class Studio
{
    constructor()
    {
        this.view=View.getInstance();this.state=State.getInstance();this.theme=this.view.theme
        this.started=performance.now();this.distance=0;this.photos=[];this.keyframes=this.read('pixel-world-sequence',[])
        this.restore();this.lastPosition=[...this.state.player.position.current];this.build();this.restoreWorldForm();this.bind();this.loading();this.saveTimer=0
    }
    build()
    {
        const el=document.createElement('div');el.className='studio-layer';el.innerHTML=`
        <nav class="main-dock" aria-label="Main navigation"><button data-studio="worlds" aria-label="Worlds"><i>⌁</i><span>Worlds</span></button><button data-suite-link="map" aria-label="Map"><i>⌖</i><span>Map</span></button><button data-studio="weather" aria-label="Weather"><i>☁</i><span>Weather</span></button><button data-suite-link="photo" aria-label="Photo"><i>◎</i><span>Photo</span></button><button data-studio="journal" aria-label="Collection"><i>✦</i><span>Collection</span><b data-collection-count>0</b></button><button data-action-link="settings" aria-label="Settings"><i>☷</i><span>Settings</span></button></nav>
        <section class="studio-panel world-builder" role="dialog" aria-modal="true" aria-labelledby="world-title"><div class="studio-head"><span><small>PROCEDURAL ORIGIN</small><strong id="world-title">Create a new world</strong></span><button data-studio-close aria-label="Close worlds">×</button></div><div class="builder-grid"><label>World name<input data-world="name" value="My Infinite World"></label><label>Seed<div><input data-world="seed" value="p"><button data-random aria-label="Random seed">↻</button><button data-copy-seed aria-label="Copy seed">⧉</button></div></label><label>Terrain style<select data-world="terrain"><option>Valleys</option><option>Mountains</option><option>Plains</option><option>Islands</option></select></label><label>Climate<select data-world="climate"><option>Temperate</option><option>Alpine</option><option>Coastal</option><option>Wild</option></select></label><label>Water level<input data-world="water" type="range" min="-20" max="20" value="-5"></label><label>Day length<input data-world="day" type="range" min="15" max="180" value="60"></label></div><div class="world-preview"><i></i><span>WORLD PREVIEW</span></div><div class="profile-list" aria-label="Saved world profiles"></div><div class="studio-actions"><button data-save-profile>Save profile</button><button class="primary" data-create-world>Generate world</button></div></section>
        <section class="studio-panel journal" role="dialog" aria-modal="true" aria-labelledby="journal-title"><div class="studio-head"><span><small>FIELD NOTES</small><strong id="journal-title">Discovery journal</strong></span><button data-studio-close aria-label="Close collection">×</button></div><div class="journal-hero"><span><small>TIME EXPLORED</small><strong data-journal="time">00:00</strong></span><span><small>DISTANCE</small><strong data-journal="distance">0 m</strong></span><span><small>HIGHEST POINT</small><strong data-journal="height">0 m</strong></span><span><small>DISCOVERIES</small><strong data-journal="discoveries">0</strong></span></div><div class="journal-cards" data-journal-cards></div><textarea data-notes aria-label="Field notes" placeholder="Write a field note…"></textarea><div class="studio-actions"><button data-copy-link>Copy location</button><button data-native-share>Share horizon</button></div></section>
        <section class="studio-panel weather-studio"><div class="studio-head"><span><small>CINEMATIC SEQUENCER</small><strong>Weather composer</strong></span><button data-studio-close>×</button></div><div class="timeline-track"><i></i><b style="left:12%">Dawn</b><b style="left:48%">Storm</b><b style="left:82%">Sunset</b></div><div class="composer-buttons"><button data-keyframe="dawn">＋ Dawn</button><button data-keyframe="storm">＋ Storm</button><button data-keyframe="snow">＋ Snow</button><button data-keyframe="sunset">＋ Sunset</button></div><label>Transition duration <input data-composer-duration type="range" min="2" max="30" value="8"><output>8 sec</output></label><div class="studio-actions"><button data-export-sequence>Export</button><button data-save-sequence>Save</button><button class="primary" data-play-sequence>▶ Preview sequence</button></div></section>
        <section class="studio-panel diagnostics"><div class="studio-head"><span><small>RENDERER HEALTH</small><strong>Diagnostics</strong></span><button data-studio-close>×</button></div><div class="diagnostic-grid"><span><small>FPS</small><strong data-diag="fps">60</strong></span><span><small>DRAW CALLS</small><strong data-diag="calls">0</strong></span><span><small>TRIANGLES</small><strong data-diag="triangles">0</strong></span><span><small>GEOMETRIES</small><strong data-diag="geometry">0</strong></span><span><small>TEXTURES</small><strong data-diag="textures">0</strong></span><span><small>CHUNKS</small><strong data-diag="chunks">0</strong></span></div><canvas width="700" height="130"></canvas><div class="studio-actions"><button data-safe-mode>Safe mode</button><button data-reset>Reset settings</button><button class="primary" data-export-diag>Export report</button></div></section>
        <section class="share-card"><strong>Share this horizon</strong><p data-share-location></p></section>
        <div class="loading-screen"><div class="loader-world"><i></i><b></b></div><small>GENERATING YOUR HORIZON</small><strong data-load-status>Preparing shaders</strong><div><i></i></div><p data-load-tip>Every hill exists because you approached it.</p></div>
        <div class="look-pad" aria-label="Look around"></div><button class="diagnostic-trigger" data-studio="diagnostics">FPS</button>`
        document.querySelector('.game').append(el);this.el=el;this.panels=[...el.querySelectorAll('.studio-panel')];this.graph=[]
    }
    bind()
    {
        this.el.querySelectorAll('[data-studio]').forEach(b=>b.onclick=()=>this.open(b.dataset.studio))
        this.el.querySelectorAll('[data-studio-close]').forEach(b=>b.onclick=()=>this.close())
        this.el.querySelectorAll('[data-suite-link]').forEach(b=>b.onclick=()=>{this.setActive(b.dataset.suiteLink);this.view.experience.open(b.dataset.suiteLink)})
        this.el.querySelector('[data-action-link]').onclick=()=>{this.close();const panel=document.querySelector('.world-panel');panel.classList.toggle('is-open');if(panel.classList.contains('is-open')){this.setActive('settings');panel.querySelector('button,input,select')?.focus()}}
        this.el.querySelector('[data-random]').onclick=()=>this.el.querySelector('[data-world="seed"]').value=Math.random().toString(36).slice(2,10)
        this.el.querySelector('[data-copy-seed]').onclick=()=>this.copy(this.el.querySelector('[data-world="seed"]').value,'Seed copied')
        this.el.querySelector('[data-create-world]').onclick=()=>this.createWorld()
        this.el.querySelector('[data-save-profile]').onclick=()=>this.saveProfile()
        this.el.querySelectorAll('[data-keyframe]').forEach(b=>b.onclick=()=>{this.keyframes.push(b.dataset.keyframe);this.view.experience.toast(`${b.dataset.keyframe} keyframe added`,'Weather composer')})
        this.el.querySelector('[data-composer-duration]').oninput=e=>e.target.nextElementSibling.textContent=`${e.target.value} sec`
        this.el.querySelector('[data-play-sequence]').onclick=()=>this.playSequence()
        this.el.querySelector('[data-export-sequence]').onclick=()=>this.download('pixel-world-sequence.json',JSON.stringify(this.keyframes,null,2))
        this.el.querySelector('[data-save-sequence]').onclick=()=>{localStorage.setItem('pixel-world-sequence',JSON.stringify(this.keyframes));this.view.experience.toast('Weather sequence saved','Composer')}
        this.el.querySelector('[data-copy-link]').onclick=()=>this.copy(this.shareURL(),'Location copied')
        this.el.querySelector('[data-native-share]').onclick=()=>this.share()
        this.el.querySelector('[data-safe-mode]').onclick=()=>{this.theme.quality='low';this.theme.events.emit('quality','low');this.close()}
        this.el.querySelector('[data-reset]').onclick=()=>{localStorage.clear();location.reload()}
        this.el.querySelector('[data-export-diag]').onclick=()=>this.download('pixel-world-diagnostics.json',JSON.stringify(this.diagnostics(),null,2))
        this.el.querySelector('[data-notes]').oninput=e=>localStorage.setItem('pixel-world-notes',e.target.value);this.el.querySelector('[data-notes]').value=localStorage.getItem('pixel-world-notes')||''
        const look=this.el.querySelector('.look-pad');let last=null;look.onpointerdown=e=>{last={x:e.clientX,y:e.clientY};look.setPointerCapture(e.pointerId)};look.onpointermove=e=>{if(!last)return;this.state.controls.pointer.deltaTemp.x+=e.clientX-last.x;this.state.controls.pointer.deltaTemp.y+=e.clientY-last.y;last={x:e.clientX,y:e.clientY}};look.onpointerup=()=>last=null
        window.addEventListener('beforeunload',()=>this.persist())
        window.addEventListener('keydown',event=>{if(event.code==='Escape')this.close()})
        window.addEventListener('pixel-world-progress',()=>this.renderJournal())
        this.el.querySelectorAll('[data-world]').forEach(input=>input.oninput=()=>this.updatePreview())
        this.renderProfiles();this.renderJournal();this.updatePreview()
    }
    open(name){this.close();const panel=name==='worlds'?this.el.querySelector('.world-builder'):name==='weather'?this.el.querySelector('.weather-studio'):name==='journal'?this.el.querySelector('.journal'):name==='diagnostics'?this.el.querySelector('.diagnostics'):null;if(panel){panel.classList.add('is-open');panel.querySelector('button,input,select,textarea')?.focus()}this.setActive(name)}
    close(){this.panels.forEach(p=>p.classList.remove('is-open'));this.setActive('')}
    createWorld(){const config=this.worldConfig(),seed=config.seed.trim()||'p';config.seed=seed;localStorage.setItem('pixel-world-current',JSON.stringify(config));this.view.experience.toast(`Seed ${seed} prepared`,'New world');location.hash=`world=${encodeURIComponent(seed)}`;location.reload()}
    worldConfig(){return Object.fromEntries([...this.el.querySelectorAll('[data-world]')].map(i=>[i.dataset.world,i.value]))}
    saveProfile(){const profiles=this.read('pixel-world-profiles',[]),config={...this.worldConfig(),id:Date.now()};profiles.push(config);localStorage.setItem('pixel-world-profiles',JSON.stringify(profiles));this.renderProfiles();this.view.experience.toast('World profile saved','Collection')}
    async playSequence(){const frames=this.keyframes.length?this.keyframes:['dawn','storm','snow','sunset'];for(const frame of frames){if(frame==='storm')this.theme.set('rainy');if(frame==='snow')this.theme.set('winter');if(frame==='dawn'||frame==='sunset'){this.theme.set('summer');this.state.day.autoUpdate=false;this.state.day.progress=frame==='dawn'?.24:.77}await new Promise(r=>setTimeout(r,1500))}}
    shareURL(){const p=this.state.player.position.current,u=new URL(location.href);u.searchParams.set('x',Math.round(p[0]));u.searchParams.set('z',Math.round(p[2]));u.searchParams.set('season',this.theme.mode);return u.toString()}
    download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
    restore(){try{const save=JSON.parse(localStorage.getItem('pixel-world-save')),params=new URLSearchParams(location.search);const x=Number(params.get('x')),z=Number(params.get('z')),hasSharedPosition=params.has('x')&&params.has('z')&&Number.isFinite(x)&&Number.isFinite(z);if(hasSharedPosition){this.state.player.position.current[0]=x;this.state.player.position.current[2]=z}else if(save){if(Number.isFinite(save.x))this.state.player.position.current[0]=save.x;if(Number.isFinite(save.z))this.state.player.position.current[2]=save.z;this.distance=Number.isFinite(save.distance)?save.distance:0;if(Number.isFinite(save.time))this.state.day.progress=save.time}const season=params.get('season')||save?.season;if(season)this.theme.set(season)}catch(error){console.warn('Save could not be restored',error)}}
    restoreWorldForm(){try{const config=JSON.parse(localStorage.getItem('pixel-world-current'));if(!config)return;this.el.querySelectorAll('[data-world]').forEach(input=>{if(config[input.dataset.world]!==undefined)input.value=config[input.dataset.world]})}catch(error){console.warn('World profile could not be restored',error)}}
    read(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}}
    setActive(name){this.el.querySelectorAll('.main-dock button').forEach(button=>button.classList.toggle('is-active',button.dataset.studio===name||button.dataset.suiteLink===name))}
    copy(text,message){if(!navigator.clipboard){this.view.experience.toast('Clipboard is unavailable','Could not copy');return}navigator.clipboard.writeText(text).then(()=>this.view.experience.toast(message,'Ready to share')).catch(()=>this.view.experience.toast('Clipboard permission was denied','Could not copy'))}
    share(){if(!navigator.share){this.view.experience.toast('Sharing is unavailable in this browser','Share');return}navigator.share({title:'Pixel World',text:'Explore my Pixel World horizon',url:this.shareURL()}).then(()=>this.view.experience.toast('Horizon shared','Share')).catch(error=>{if(error.name!=='AbortError')this.view.experience.toast('Sharing could not be completed','Share')})}
    updatePreview(){const p=this.el.querySelector('.world-preview'),terrain=this.el.querySelector('[data-world="terrain"]').value,climate=this.el.querySelector('[data-world="climate"]').value,water=this.el.querySelector('[data-world="water"]').value;p.dataset.terrain=terrain.toLowerCase();p.dataset.climate=climate.toLowerCase();p.style.setProperty('--preview-water',`${55-Math.max(-20,Math.min(20,water))*0.7}%`);p.querySelector('span').textContent=`${terrain.toUpperCase()} · ${climate.toUpperCase()}`}
    renderProfiles(){const list=this.el.querySelector('.profile-list'),profiles=this.read('pixel-world-profiles',[]);list.innerHTML=profiles.length?'<small>SAVED WORLDS</small>':'';profiles.forEach(profile=>{const row=document.createElement('div');row.innerHTML=`<span><strong>${profile.name||'Untitled world'}</strong><small>${profile.terrain} · ${profile.climate} · ${profile.seed}</small></span><button>Load</button><button aria-label="Delete ${profile.name||'world'}">×</button>`;const buttons=row.querySelectorAll('button');buttons[0].onclick=()=>{this.el.querySelectorAll('[data-world]').forEach(input=>{if(profile[input.dataset.world]!==undefined)input.value=profile[input.dataset.world]});this.updatePreview();this.view.experience.toast('Profile loaded','Worlds')};buttons[1].onclick=()=>{localStorage.setItem('pixel-world-profiles',JSON.stringify(profiles.filter(item=>item.id!==profile.id)));this.renderProfiles();this.view.experience.toast('Profile removed','Worlds')};list.append(row)})}
    renderJournal(){const discoveries=this.view.experience.discoveries,photos=this.view.experience.photos,count=discoveries.length;this.el.querySelector('[data-journal="discoveries"]').textContent=count;this.el.querySelector('[data-collection-count]').textContent=count;const cards=this.el.querySelector('[data-journal-cards]');cards.innerHTML='';const items=discoveries.slice(0,9);if(!items.length)cards.innerHTML='<p class="empty-state">Your discoveries, landmarks, journeys, and photos will appear here.</p>';items.forEach(item=>{const article=document.createElement('article');article.innerHTML=`<i>${item.type==='Wildlife'?'⌁':item.type==='Photo'?'◎':item.type==='Journey'?'△':'✦'}</i><small>${item.type}</small><strong>${item.title}</strong><p>${item.details?.rarity||item.details?.season||'Recorded in your world'}</p>`;cards.append(article)});this.photos=photos}
    persist(){const p=this.state.player.position.current;localStorage.setItem('pixel-world-save',JSON.stringify({x:p[0],z:p[2],season:this.theme.mode,time:this.state.day.progress,distance:this.distance}))}
    loading(){const screen=this.el.querySelector('.loading-screen'),bar=screen.querySelector('div>i'),status=screen.querySelector('[data-load-status]'),started=performance.now();const check=()=>{const chunks=this.state.chunks.allChunks.size,ready=[...this.state.terrains.terrains.values()].some(terrain=>terrain.ready),elapsed=performance.now()-started;const p=ready?100:Math.min(92,18+chunks*5+elapsed/160);bar.style.width=`${p}%`;status.textContent=p<35?'Compiling atmosphere':p<70?'Sculpting terrain':p<100?'Growing the world':'Ready to explore';if(p===100){setTimeout(()=>screen.classList.add('is-hidden'),250);return}requestAnimationFrame(check)};requestAnimationFrame(check)}
    diagnostics(){const info=this.view.renderer.instance.info;return{fps:this.fps||60,drawCalls:info.render.calls,triangles:info.render.triangles,geometries:info.memory.geometries,textures:info.memory.textures,chunks:this.state.chunks.allChunks.size,quality:this.theme.quality,userAgent:navigator.userAgent}}
    drawGraph(){const c=this.el.querySelector('.diagnostics canvas'),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.strokeStyle='#74d6b3';x.beginPath();this.graph.forEach((v,i)=>{const px=i/(this.graph.length-1)*c.width,py=c.height-Math.min(v,80)/80*c.height;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}
    update()
    {
        const p=this.state.player.position.current,dx=p[0]-this.lastPosition[0],dz=p[2]-this.lastPosition[2];this.distance+=Math.hypot(dx,dz);this.lastPosition=[...p];this.saveTimer+=this.state.time.delta;if(this.saveTimer>5){this.persist();this.saveTimer=0}
        const elapsed=(performance.now()-this.started)/1000;this.el.querySelector('[data-journal="time"]').textContent=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(Math.floor(elapsed%60)).padStart(2,'0')}`;this.el.querySelector('[data-journal="distance"]').textContent=`${Math.round(this.distance)} m`;this.el.querySelector('[data-journal="height"]').textContent=`${Math.max(0,Math.round(p[1]))} m`;this.el.querySelector('[data-share-location]').textContent=`${Math.round(p[0])}, ${Math.round(p[2])} · ${this.theme.mode}`
        this.fps=Math.round(1/Math.max(this.state.time.delta,.001));if(Math.random()<.05){const d=this.diagnostics();for(const[k,v]of Object.entries({fps:d.fps,calls:d.drawCalls,triangles:d.triangles,geometry:d.geometries,textures:d.textures,chunks:d.chunks})){const e=this.el.querySelector(`[data-diag="${k}"]`);if(e)e.textContent=v.toLocaleString()}this.graph.push(d.fps);if(this.graph.length>100)this.graph.shift();this.drawGraph()}
    }
}
